In [2]:
import pandas as pd

In [3]:
epic_may = pd.read_excel('/home/trishalaswain/ClientData/SCP/ML_DATA/EPIC_SCP/MAY/EPIC_MAY_ML_DATA_FINAL.xlsx', index_col=False)

In [4]:
epic_may['month'] = '2023-05'

In [12]:
epic_may.facility = epic_may.facility.astype('str')
epic_june.facility = epic_june.facility.astype('str')
epic_july.facility = epic_july.facility.astype('str')
epic_aug.facility_code = epic_aug.facility_code.astype('str')
epic_may.columns

Index(['facility', 'encounter_id', 'account_number', 'DIAGNOSIS',
       'DIFF_DIAGNOSIS', 'DIAGNOSTIC_PROCEDURES', 'DISPOSITION',
       'ADMISSION_STATUS', 'MDM_SENTS', 'EANDM_Suggested', 'EANDM_Final',
       'ADDENDUM', 'ADMIT', 'clean_eandm_suggested', 'clean_eandm_final',
       'TIME_CASES', 'month'],
      dtype='object')

In [5]:
cols_to_use = ['facility', 'month', 'encounter_id', 'account_number', 'MDM_SENTS']

In [13]:
epic_may_final = epic_may[(epic_may.facility == '2512') | (epic_may.facility == '2474')][cols_to_use].reset_index()

In [14]:
epic_may_final

,index,facility,month,encounter_id,account_number,MDM_SENTS
0,80524,2474,2023-05,7275645,88838485,diagnosis date adhd (attention deficit hyperac...
1,80525,2474,2023-05,7082879,88506459,diagnosis date arthritis dementia hepatitis c ...
2,80526,2474,2023-05,7329601,88871452,"procedures labs reviewed urinalysis, reflex to..."
3,80527,2474,2023-05,7085226,88571235,diagnosis date asthma history reviewed. no per...
4,80528,2474,2023-05,7087372,88633151,diagnosis date diabetes mellitus type ii 1998 ...
...,...,...,...,...,...,...
3955,84479,2474,2023-05,7306885,88857125,diagnosis date allergic rhinitis anemia anxiet...
3956,84480,2474,2023-05,5397376,87428809,diagnosis date atherosclerosis of aorta noted ...
3957,84481,2474,2023-05,7084541,88554864,procedures labs reviewed rsv antigen detection...
3958,84482,2474,2023-05,7088351,88697321,procedures labs reviewed - no data to display ...
3959,84483,2474,2023-05,7087437,88633090,procedures labs reviewed sars-cov-2 rdrp gene ...

In [6]:
epic_june = pd.read_excel('/home/trishalaswain/ClientData/SCP/ML_DATA/EPIC_SCP/JUNE/EPIC_JUNE_ML_DATA_FINAL.xlsx', index_col=False)

In [7]:
epic_june.columns
epic_june['month'] = '2023-06'

In [15]:
epic_june_final = epic_june[(epic_june.facility == '2512') | (epic_june.facility == '2474')][cols_to_use].reset_index()

In [16]:
epic_june_final

,index,facility,month,encounter_id,account_number,MDM_SENTS
0,103551,2474,2023-06,8040333,89375618,diagnosis date anemia hypertension no meds wit...
1,103552,2474,2023-06,7687295,89143476,diagnosis date allergy hypertension no past su...
2,103553,2474,2023-06,7939213,89300338,diagnosis date abscess procedures labs reviewe...
3,103554,2474,2023-06,8119017,89423776,procedures labs reviewed cbc w/ auto different...
4,103555,2474,2023-06,7518138,89014151,"diagnosis date alcohol abuse, continuous anxie..."
...,...,...,...,...,...,...
3940,107491,2474,2023-06,7576563,89060753,diagnosis date asthma history reviewed. no per...
3941,107492,2474,2023-06,7850201,89243803,procedures labs reviewed cbc w/ auto different...
3942,107493,2474,2023-06,7745558,89189936,procedures labs reviewed comprehensive metabol...
3943,107494,2474,2023-06,7745505,89189942,diagnosis date ams (altered mental status) 08/...
3944,107495,2474,2023-06,7628852,89094876,diagnosis date hypertension procedures labs re...

In [8]:
epic_july = pd.read_excel('/home/trishalaswain/ClientData/SCP/ML_DATA/EPIC_SCP/JULY/EPIC_JULY_ML_DATA_FINAL.xlsx', index_col=False)

In [9]:
epic_july.columns
epic_july['month'] = '2023-07'

In [17]:
epic_july_final = epic_july[(epic_july.facility == '2512') | (epic_july.facility == '2474')][cols_to_use].reset_index()

In [18]:
epic_july_final

,index,facility,month,encounter_id,account_number,MDM_SENTS
0,15298,2512,2023-07,8543243,89418311,procedures labs reviewed cbc w/ auto different...
1,15299,2512,2023-07,8543243,89418311,procedures labs reviewed cbc w/ auto different...
2,15300,2512,2023-07,8564799,89549411,diagnosis date abnormal pap smear allergy asth...
3,15301,2512,2023-07,8564799,89549411,diagnosis date abnormal pap smear allergy asth...
4,15302,2512,2023-07,8564758,89549302,diagnosis date allergic conjunctivitis asthma ...
...,...,...,...,...,...,...
7320,42916,2474,2023-07,8591706,89746354,procedures labs reviewed cbc w/ auto different...
7321,42917,2474,2023-07,8478036,89674765,diagnosis date drug addiction history reviewed...
7322,42918,2474,2023-07,8503898,89692118,diagnosis date chf (congestive heart failure) ...
7323,42919,2474,2023-07,8477408,89674991,procedures labs reviewed poct strep a molecula...
7324,42920,2474,2023-07,8214980,89498452,labs reviewed poct urine pregnancy medications...

In [10]:
epic_aug = pd.read_excel('/home/trishalaswain/ClientData/SCP/ML_DATA/EPIC_SCP/AUG/EPIC_AUG_FINAL.xlsx', index_col=False)

In [11]:
epic_aug.columns
epic_aug['month'] = '2023-08'
new_cols= ['facility_code', 'month', 'encounter_id', 'account_number', 'MDM_SENTS']

In [19]:
epic_aug_final = epic_aug[(epic_aug.facility_code == '2512') | (epic_aug.facility_code == '2474')][new_cols].reset_index()

In [20]:
epic_aug_final

,index,facility_code,month,encounter_id,account_number,MDM_SENTS
0,107865,2512,2023-08,8543300,89434302,procedures labs reviewed - no data to display ...
1,107866,2512,2023-08,8586864,89756756,final diagnoses: [r07.9] chest pain [r07.89] c...
2,107867,2512,2023-08,8819516,89929770,diagnosis date arthritis bronchitis covid-19 d...
3,107868,2512,2023-08,9290585,90225333,diagnosis date anxiety deaf hiv (human immunod...
4,107869,2512,2023-08,8813940,89913813,diagnosis date acquired hypothyroidism 8/12/20...
...,...,...,...,...,...,...
10185,128709,2474,2023-08,8834381,89919235,procedures labs reviewed comprehensive metabol...
10186,128710,2474,2023-08,8865026,89935978,diagnosis date anxiety cts (carpal tunnel synd...
10187,128711,2474,2023-08,9313019,90229046,diagnosis date anemia hypertension nuclear scl...
10188,128712,2474,2023-08,8834710,89919197,diagnosis date abnormal ekg chlamydia constipa...
10189,128713,2474,2023-08,9311402,90210211,diagnosis date constrictive pericarditis liver...

In [21]:
epic_aug_final.rename(columns={'facility_code': 'facility'}, inplace=True)

In [24]:
pd.concat([epic_may_final, epic_june_final, epic_july_final, epic_aug_final], axis=0).month.value_counts()

2023-08    10190
2023-07     7325
2023-05     3960
2023-06     3945
Name: month, dtype: int64

In [ ]:
df_2512 = df[df.facility == '2512']

In [ ]:
df_2512.drop(labels=['index', 'level_0'], axis=1, inplace=True)

In [ ]:
df_2512.reset_index(inplace=True)

In [ ]:
df_2512.to_excel('/home/trishalaswain/Documents/AGS_PROJECTS/zalak/2512_MAY_JUNE_JUL_AUG.xlsx')

In [ ]:
df_2474 = df[df.facility == '2474']

In [ ]:
df_2474.drop(labels=['index', 'level_0'], axis=1, inplace=True)

In [ ]:
df_2474.reset_index(inplace=True)

In [ ]:
df_2474.to_excel('/home/trishalaswain/Documents/AGS_PROJECTS/zalak/2474_MAY_JUNE_JUL_AUG.xlsx')

In [ ]:
df_2474.month.value_counts()