In [1]:
import pandas as pd
import re

In [2]:
import os

# folder path
dir_path = r'/home/trishalaswain/Downloads/PH_01_to_31_Jan_tsv/'

# list to store files
res = []

# Iterate directory
for path in os.listdir(dir_path):
    # check if current path is a file
    if os.path.isfile(os.path.join(dir_path, path)) and str(path).endswith(".tsv") and not str(path).endswith("HCPCS.tsv") and not str(path).endswith("CPT.tsv") and not str(path).endswith("CM.tsv")  and not str(path).endswith("EANDM.tsv"):
        print(path)
        res.append(dir_path + path)

PH-AHE-Alvarado Hospital EMA-2023-01-01-2023-01-31.tsv
PH-HEMAG-Hollywood EMA Group-2023-01-01-2023-01-31.tsv
PH-PIMG-Palomar Intensivist Medical Group, Inc.-2023-01-01-2023-01-31.tsv
PH-LPIH-La Palma Intercommunity Hospital-2023-01-01-2023-01-31.tsv
PH-MMC-Montclair Hospital Medical Center-2023-01-01-2023-01-31.tsv
PH-HBH-Huntington Beach Hospital-2023-01-01-2023-01-31.tsv
PH-SDCH-San Dimas Community Hospital-2023-01-01-2023-01-31.tsv
PH-PEP-Palomar Emergency Physicians, Inc.-2023-01-01-2023-01-31.tsv
PH-HIG-Hollywood Intensivist Group-2023-01-01-2023-01-31.tsv
PH-TMC-Tarzana Medical Center-2023-01-01-2023-01-31.tsv
PH-SRMC-Shasta Regional Medical Center-2023-01-01-2023-01-31.tsv
PH-CMC-College Medical Center-2023-01-01-2023-01-31.tsv
PH-CHMC-Centinela Hospital Medical Center-2023-01-01-2023-01-31.tsv
PH-EHMC-Encino Hospital Medical Center-2023-01-01-2023-01-31.tsv
PH-CCHP-Community Hospital of Huntington Park-2023-01-01-2023-01-31.tsv
PH-CELA-East Los Angeles Doctors Hospital-2023-01-01-2023-01-31.tsv
PH-CEMA-Corona Regional Emergency Medical Associates-2023-01-01-2023-01-31.tsv
PH-SOH-Sherman Oaks Hospital-2023-01-01-2023-01-31.tsv
PH-CHINO-Chino Valley Medical Center-2023-01-01-2023-01-31.tsv
PH-RMHG-Redondo Memorial Hospital of Gardena-2023-01-01-2023-01-31.tsv
PH-LAMC-Los Alamos Medical Center-2023-01-01-2023-01-31.tsv
PH-VPH-Valley Presbyterian Hospital-2023-01-01-2023-01-31.tsv

In [3]:
i = 0
l = []

for file in res:
    
    # filename = re.findall("SCP-\d.*", file)
    filename = re.findall("PH-.*", file)

    # print(str(filename))
    df = pd.read_table(file, index_col = False)
    # df['serviceDate'] = pd.to_datetime( df.serviceDate)
    # df = df[df.serviceDate>='2023-01-01']
    # # df = df.reset_index()
    # df = df[if '99281' in df.EANDM_Final]
    
    # concatenating df1 and df2 along rows
    l.append(df)
    
df_final = pd.concat(l)

In [4]:
df_final

,id,physicianId,serviceDate,processingDate,admissionDate,userId,processId,lastCodingDate,month,visitType,...,EANDM_Rejected_Count,EANDM_Added_Count,HCPCS_Final,HCPCS_Accepted,HCPCS_Rejected,HCPCS_Added,HCPCS_Suggested,HCPCS_Accepted_Count,HCPCS_Rejected_Count,HCPCS_Added_Count
0,4096538,29865,2022-12-20 00:00:00.0,2022-12-23 18:10:33.0,2022-12-20 00:00:00.0,6160,1,2023-01-01 15:08:39.0,2023-01,New Patient,...,0,0,[],[],[],[],[],0,0,0
1,4096580,29865,2022-12-20 00:00:00.0,2022-12-23 18:12:14.0,2022-12-20 00:00:00.0,6160,1,2023-01-01 15:13:04.0,2023-01,New Patient,...,1,1,[],[],[],[],[],0,0,0
2,4097111,29865,2022-12-20 00:00:00.0,2022-12-23 19:03:16.0,2022-12-20 00:00:00.0,6160,1,2023-01-01 15:17:39.0,2023-01,New Patient,...,0,0,[],[],[],[],[],0,0,0
3,4099376,29865,2022-12-20 00:00:00.0,2022-12-23 21:18:01.0,2022-12-20 00:00:00.0,6160,1,2023-01-01 15:23:24.0,2023-01,New Patient,...,1,1,[],[],[],[],[],0,0,0
4,4099388,29865,2022-12-20 00:00:00.0,2022-12-23 21:18:21.0,2022-12-20 00:00:00.0,6160,1,2023-01-01 15:28:04.0,2023-01,New Patient,...,1,1,[],[],[],[],[],0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4383,4814385,27904,2023-01-24 00:00:00.0,2023-01-27 08:17:00.0,2023-01-24 16:08:00.0,5707,1,2023-01-31 21:01:15.0,2023-01,New Patient,...,0,0,[],[],[],[],[],0,0,0
4384,4814390,27904,2023-01-24 00:00:00.0,2023-01-27 08:17:02.0,2023-01-24 13:07:00.0,5707,1,2023-01-31 21:12:27.0,2023-01,New Patient,...,1,1,[],[],[],[],[],0,0,0
4385,4814391,27904,2023-01-24 00:00:00.0,2023-01-27 08:17:03.0,2023-01-24 16:23:00.0,5707,1,2023-01-31 21:16:41.0,2023-01,New Patient,...,0,0,[],[],[],[],[],0,0,0
4386,4814392,27904,2023-01-24 00:00:00.0,2023-01-27 08:17:03.0,2023-01-24 20:43:00.0,5707,1,2023-01-31 21:34:53.0,2023-01,New Patient,...,0,0,[],[],[],[],[],0,0,0
4387,4814397,27904,2023-01-24 00:00:00.0,2023-01-27 08:17:06.0,2023-01-24 13:17:00.0,5707,1,2023-01-31 21:40:18.0,2023-01,New Patient,...,1,1,[],[],[],[],[],0,0,0

In [5]:
df_final.to_excel('/home/trishalaswain/Downloads/ph_overall_jan.xlsx')

In [6]:
df_final['serviceDate'] = pd.to_datetime( df_final.serviceDate)

In [8]:
df_final = df_final[df_final.serviceDate>='2023-01-01']

In [9]:
df_final.facilityName.value_counts()

Palomar Emergency Physicians, Inc.              8749
Valley Presbyterian Hospital                    3252
Tarzana Medical Center                          2957
Centinela Hospital Medical Center               2719
Chino Valley Medical Center                     2515
Corona Regional Emergency Medical Associates    1992
Community Hospital of Huntington Park           1723
Redondo Memorial Hospital of Gardena            1703
Montclair Hospital Medical Center               1554
Alvarado Hospital EMA                           1388
Sherman Oaks Hospital                           1298
Hollywood EMA Group                             1177
Shasta Regional Medical Center                   867
La Palma Intercommunity Hospital                 866
East Los Angeles Doctors Hospital                818
Huntington Beach Hospital                        774
College Medical Center                           768
Palomar Intensivist Medical Group, Inc.          724
San Dimas Community Hospital                     617
Encino Hospital Medical Center                   581
Los Alamos Medical Center                        429
Hollywood Intensivist Group                      188
Name: facilityName, dtype: int64

In [14]:
def get_220_counts(x):
    return len([code for code in x.fillna('') if '99220' in code])
    
df_final.groupby('facilityName').agg({'EANDM_Final' : get_220_counts, 'EANDM_Suggested': get_220_counts})

<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>

                                              EANDM_Final  EANDM_Suggested
facilityName
Alvarado Hospital EMA                                   0                0
Centinela Hospital Medical Center                       0                0
Chino Valley Medical Center                             0                0
College Medical Center                                  0                0
Community Hospital of Huntington Park                   0                0
Corona Regional Emergency Medical Associates            0                0
East Los Angeles Doctors Hospital                       0                0
Encino Hospital Medical Center                          0                0
Hollywood EMA Group                                     0                0
Hollywood Intensivist Group                             0                0
Huntington Beach Hospital                               0                0
La Palma Intercommunity Hospital                        0                0
Los Alamos Medical Center                               0                0
Montclair Hospital Medical Center                       0                0
Palomar Emergency Physicians, Inc.                      0                0
Palomar Intensivist Medical Group, Inc.                 0                0
Redondo Memorial Hospital of Gardena                    0                0
San Dimas Community Hospital                            0                0
Shasta Regional Medical Center                          0                0
Sherman Oaks Hospital                                   0                0
Tarzana Medical Center                                  0                0
Valley Presbyterian Hospital                            0                0

In [11]:
df_final[(df_final.EANDM_Final.fillna('').str.contains('99220'))
         & (df_final.facilityName.str.contains('Alvarado'))
         & ~(df_final.EANDM_Suggested.fillna('').str.contains('99220'))][['accountNumber', 'EANDM_Final', 'EANDM_Suggested']]

Empty DataFrame
Columns: [accountNumber, EANDM_Final, EANDM_Suggested]
Index: []

In [12]:
df_final.to_excel('/home/trishalaswain/Downloads/ph-overallData.xlsx')

In [ ]:
# df_final1 = df_final[df_final['serviceDate'] >= '2023-01-01']

In [ ]:
# df_final.EANDM_Final.value_counts()

In [ ]:
# df_final1 = df_final[lambda df_final['EANDM_Rejected']: df_final['EANDM_Rejected'] if ('99220' in df_final['EANDM_Rejected'])]

In [ ]:
 # lambda x : x if(x >= 0)

In [ ]:
# df_final1

In [ ]:
# df_final2 = df_final1[df_final1['EANDM_Final'] == '99281']

In [ ]:
df_final3 = df_final1[["serviceDate","facilityCode","facilityName","accountNumber","EANDM_Final","EANDM_Suggested"]]

In [ ]:
df_final3.to_excel('/home/trishalaswain/Downloads/99281.xlsx')

In [ ]:
df_final3

In [ ]:
86773277